### ISSUE TITLE
Error while installing on Linux Mint 18.2 ( Ubuntu 16.04)

### ISSUE THREAD

**Issue by saurabh-3896** [llSourcell/sirajcoin#10]
the output of  "npm i -g sirajcoin" is in this gist

https://gist.github.com/saurabh-3896/eac7d5cfc741ddd62a057f7f6bb11fd4

**Comment by ravindrabarthwal** [comment]
Hi Saurabh, 
I had a problem with installing as well on azure ubuntu vm . I followed the below steps and everything is working fine. 
Step 1: Make sure your machine has make and g++ installed. Use `sudo apt-get make g++`
Step 2: Use `sudo npm i -g sirajcoin`

Try these steps and let me know.

**Comment by 1nF0rmed** [comment]
Do you mean `sudo apt-get install make g++`?

**Comment by ravindrabarthwal** [comment]
Yup. Updated my comment.

**Comment by saurabh-3896** [comment]
0. sudo apt-get install make g++
1. sudo chown -R $USER:$(id -gn $USER) /home/heimdall/.config 
2. sudo npm i -g --unsafe-perm sirajcoin

following the above commands solved my problem
