### ISSUE TITLE
error in installing SirajCoin (npm -v 5.6.0 and node -v v9.4.0)

### ISSUE THREAD

**Issue by vdt** [llSourcell/sirajcoin#15]
npm i -g sirajcoin (on mac gives)
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/bin/sirajcoin-node -> /usr/local/lib/node_modules/sirajcoin/bin/node.js
/usr/local/bin/sirajcoin -> /usr/local/lib/node_modules/sirajcoin/bin/wallet.js

> ed25519-supercop@1.0.2 install /usr/local/lib/node_modules/sirajcoin/node_modules/ed25519-supercop
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/vikramdutt/miniconda3/bin/python" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:264:7)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:363:11)
gyp ERR! stack     at Socket.emit (events.js:160:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:559:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sirajcoin/node_modules/ed25519-supercop
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ed25519-supercop@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ed25519-supercop@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ravindrabarthwal** [comment]
Looking to this section of error

gyp ERR! stack Error: Python executable "/Users/vikramdutt/miniconda3/bin/python" is v3.6.1, which is ```
not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

It seems you need to install python 2.7 and I believe you are using python 3+

**Comment by danielsan** [comment]
For node 9.4
https://github.com/llSourcell/sirajcoin/issues/14#issuecomment-359184363

**Comment by danielsan** [comment]
For node 5.6
But, anyway, if you read the README https://github.com/llSourcell/sirajcoin#installing-the-sirajcoin-wallet
you'll see that the minimum requirement is 

> Node.js v7.6.0

**Comment by Saurabh3333** [comment]
Same issue with Node.js v8.x

**Comment by Saurabh3333** [comment]
@danielsan  Not working with Node.js v8.x
Same error again

**Comment by mappum** [comment]
Version 1.0.7 of sirajcoin now makes the problematic `ed25519-supercop` module an optional dependency, so this should fix your problems.

Please try installing this version with:
```bash
npm i -g sirajcoin@1.0.7
```

You may reopen the issue if you still have problems.

**Comment by Saurabh3333** [comment]
@mappum @danielsan  On doing this I am not getting the previous error but the installing gone into a never-ending process. 
![capture](https://user-images.githubusercontent.com/20047701/35187247-dac0796c-fe46-11e7-85cd-12cc96d4f145.PNG)
