### ISSUE TITLE
Can't install sirajcoin package with node js

### ISSUE THREAD

**Issue by thibo73800** [llSourcell/sirajcoin#3]
Hi, I can't install the sirajcoin package....

`nodejs -v`
v8.9.4

`npm -v`
5.6.0

`
sudo npm i -g sirajcoin
`

`
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/bin/sirajcoin -> /usr/lib/node_modules/sirajcoin/bin/wallet.js
/usr/bin/sirajcoin-node -> /usr/lib/node_modules/sirajcoin/bin/node.js

> ed25519-supercop@1.0.2 install /usr/lib/node_modules/sirajcoin/node_modules/ed25519-supercop
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/sirajcoin/node_modules/ed25519-supercop/build'
gyp ERR! System Linux 4.13.0-26-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/sirajcoin/node_modules/ed25519-supercop
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/sirajcoin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ed25519-supercop@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ed25519-supercop@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thibault/.npm/_logs/2018-01-20T12_02_32_427Z-debug.log

`

**Comment by mappum** [comment]
Try installing the build dependencies:
```
sudo apt install build-essential python
```

**Comment by mappum** [comment]
It looks like you're installing from root, you should run the `npm i -g sirajcoin` command without sudo.

**Comment by christiandbf** [comment]
I have the same problem trying to install it on MacOS with the same versions of Node and NPM.

**Comment by christiandbf** [comment]
@mappum it is a global package, if you don't use sudo it does not work

**Comment by mappum** [comment]
@christiandbf To fix permissions problems, read this: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by prisar** [comment]
I am getting this error after while i am trying to install sirajcoin:

```npm ERR! code E404
npm ERR! 404 Not Found: siracoin@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-01-20T13_23_02_657Z-debug.log

**Comment by christiandbf** [comment]
@mappum it is strange, it is working if I try to install it in other folder without sudo. Why it happen?

**Comment by mappum** [comment]
Version 1.0.7 of sirajcoin now makes the problematic `ed25519-supercop` module an optional dependency, so this should fix your problems.

Please try installing this version with:
```bash
npm i -g sirajcoin@1.0.7
```

You may reopen the issue if you still have problems.

**Comment by prisar** [comment]
Yes, it worked
