### ISSUE TITLE
Possibly Violates YouTubes Terms of Service

### ISSUE THREAD

**Issue by TheRedMudder** [llSourcell/sirajcoin#30]
Incentivizing new subscribers and incentiving existing subscribers to refer new ones by giving them a Sirajcoin may be considered purchasing subscribers. Although cash is not used, it is a "third party marketplace." This is possibly against YouTube's TOS. 

> Additionally, **services that attempt to boost YouTube subscriber**  numbers through automated means or **via a marketplace**  violate our Terms of Service
  
Source: https://support.google.com/youtube/answer/6051134?hl=en
I am not against the idea of increasing the growth of the AI community, but I don't want YouTube to delete your channel.

**Comment by bharadwajpro** [comment]
There is no **automation** of subscribing to a YouTube channel. SirajCoin is just recording who referred whom and incentivizing the referrer(which has no real value, only some power to take decisions). If you say this is violating TOS, then what about some top youtubers who run giveaways on gleam.io which asks the user to subscribe to a channel to join the giveaway?

**Comment by TheRedMudder** [comment]
Cool.   I just checkout gleam.io, they encourage user to comment and subscribe to enter contest without getting flagged. So, awesome. Also, I never mentioned automation.
