### ISSUE TITLE
Showing errors while trying to run in Ubuntu 16.04

### ISSUE THREAD

**Issue by LordSomen** [llSourcell/sirajcoin#33]
/usr/local/bin/sirajcoin -> /usr/local/lib/node_modules/sirajcoin/bin/wallet.js
/usr/local/bin/sirajcoin-node -> /usr/local/lib/node_modules/sirajcoin/bin/node.js

> secp256k1@3.4.0 install /usr/local/lib/node_modules/sirajcoin/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.4.0 rebuild /usr/local/lib/node_modules/sirajcoin/node_modules/secp256k1
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sirajcoin/node_modules/secp256k1/build'
gyp ERR! System Linux 4.13.0-16-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sirajcoin/node_modules/secp256k1
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌─────────────────────────────────────────────────────────────┐
│                   npm update check failed                   │
│             Try running with sudo or get access             │
│            to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) /home/soumyajit/.config │
└─────────────────────────────────────────────────────────────┘
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> utp-native@1.6.2 install /usr/local/lib/node_modules/sirajcoin/node_modules/utp-native
> node-gyp-build

> leveldown@1.7.2 install /usr/local/lib/node_modules/sirajcoin/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.7.2-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/soumyajit/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v57-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/soumyajit/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v57-linux-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sirajcoin/node_modules/leveldown/build'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sirajcoin/node_modules/leveldown/build'
gyp ERR! System Linux 4.13.0-16-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sirajcoin/node_modules/leveldown
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/sirajcoin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/soumyajit/.npm/_logs/2018-01-21T14_53_15_042Z-debug.log

**Comment by hdon** [comment]
As the log shows:

```
EACCES: permission denied, mkdir 
```

You need to invoke commands with a user that has privileges necessary to carry them out.

Try `sudo`.

Also it's a good idea generally to include the command that generates a given output. I'm guessing you ran `npm i -g sirajcoin`.

**Comment by LordSomen** [comment]
No no I have run the command with sudo , but it is showing this error..

**Comment by hdon** [comment]
@LordSomen if you'd like, you can message me on the slack at https://programming-wizards.slack.com/ and we can get it figured out

**Comment by hdon** [comment]
FYI it is not recommended to sudo npm at all. I just learned this, and while I have some mixed feelings about it, looking through the node-gyp code suggests that for now, it's the path of least resistance.

https://givan.se/do-not-sudo-npm/

**Comment by LordSomen** [comment]
okk thanks @hdon its solved the problem.
