### ISSUE TITLE
Add steps to follow for generating Sirajcoin address

### ISSUE THREAD

**Issue by prisar** [llSourcell/sirajcoin#37]
I cannot generate my address. Please provide a tutorial to generate the address.

**Comment by Bearlakeburton** [comment]
First, you'll need to generate a Sirajcoin address.

After you've installed the wallet, you can see your address by running:

$ sirajcoin balance

**Comment by Bearlakeburton** [comment]
when you do that it should show you your public key...i think

**Comment by prisar** [comment]
i did that previously and i was having some problem in getting the address. But, now i am getting the address.

**Comment by hdon** [comment]
@prisar your issue seems resolved. Care to close the issue?

**Comment by prisar** [comment]
Yes, i am closing the issue
